### ISSUE TITLE
Palette page

### ISSUE THREAD

**Issue by Skagoo** [catppuccin/website#16]
I noticed there's no page yet behind the PALETTE link, nor can I find any work in progress towards this feature.
Has any work been done on this, if not, is there an idea yet of what it should look like and what it should offer?

If not, I'd be interested to start this.

**Comment by nekowinston** [comment]
It exists on the `dev` branch: https://website-git-dev-catppuccin.vercel.app/palette

**Comment by Skagoo** [comment]
Wonder how I missed that... looks great! I'm assuming this doesn't need any extra work?

**Comment by nekowinston** [comment]
It needs some fixes, but i'm planning to get to those on the weekend. I'm welcoming feedback & ideas tho 🙂
