### ISSUE TITLE
What's the MVP?

### ISSUE THREAD

**Issue by sgoudham** [catppuccin/website#18]
@backwardspy, @ghostx31 and I were discussing this alongside some maintainers in the discord `#dev` channel. We came to the conclusion that we should ideally ship the website as-is. 

However, we haven't personally been involved in the development of the website. **Are there any critical bugs that are currently stopping us from shipping it as it is now?**

I'd like to note down a list of the general TODOs if that's alright, I don't think we have documented that anywhere. Also while I'm here, I think @catppuccin/staff need permission to view Vercel builds and have the ability to kick off new ones etc.

## Stuff that I think we want

- [ ] Nightly builds updating the list of ports based on the `ports.yml`
- [ ] Unified contributing guide (I'd imagine this involves updating `.github/CONTRIBUTING.md` and creating a sub-page on the website to point towards it. In my eyes, it's killing two birds with one stone)
- [ ] Having a `/maintainers` sub-page that recognises all of our maintainers for their efforts. I also imagine there's some overlap here with the `catppuccin/community` repository as we were discussing having a table of all the maintainers over there.

**Comment by Oman395** [comment]
Why would we need to rebuild nightly? Wouldn't it be easier to just have a script that gets ports.yml, then constructs the content on the page with that?

**Comment by Oman395** [comment]
Also the palette link should probably do something lol

**Comment by sgoudham** [comment]
Hey :wave: @Oman395 

To my limited knowledge, I think we are only doing it at build time, I believe we'd need a way of keeping it up to date. Whether it's a dynamic job that the page manages or nightly builds that retrieve the latest port list every day is up to us I guess.

I personally opt for a nightly build because it reduces code complexity within the application itself. It's also important to note updates to the `ports.yml` are infrequent so I don't see much value in trying to make it all dynamic and updated in real-time.

I should dive into the code though :p

**Comment by Oman395** [comment]
https://github.com/catppuccin/website/blob/main/src/pages/ports/[slug].tsx

Based on my very rough understanding of next, it looks like the functions that call getPorts are constant, so they would be set during build-- I'll clone it and see what happens if I just delete the const keyword

**Comment by ghostx31** [comment]
Yeah, I say we go for build once a day or once every other day since we don't really update `ports.yml` a lot and we don't need to make any code changes to the website for this.

**Comment by nekowinston** [comment]
I'll respond to this issue in detail later, but for now I should just mention that **the current dev branch is not expected to build**. We've made schema changes to the `ports.yml` file, and the logic for parsing it hasn't been updated yet.
