### ISSUE TITLE
Add a more accessable icon system.

### ISSUE THREAD

**Issue by BlueFalconHD** [catppuccin/website#3]
Maybe add it to something like `meta.json` per port. This would make it much easier than hardcoding icons in the icons typescript file. This could be formatted like:
```json
{
    "websiteIcon": "siArchlinux",
    "websiteColor": "blue"
}
```
This would provide better looks for the website and an easier way to maintain icons. The icon would still default to the normal default. The meta.json could also be added to `@catppuccin/template`

**Comment by nekowinston** [comment]
Yeah this is all still in WIP, I'll use a JSON file instead.

**Comment by BlueFalconHD** [comment]
Cool. Maybe it would be better to add it to the .yaml for the cli?

**Comment by nekowinston** [comment]
That's the exact plan. 🙂

**Comment by BlueFalconHD** [comment]
> That's the exact plan. 🙂

Awesome. For some reason i come up with ideas that already exist. :octocat:
